### PR TITLE
Update usage of React suspense

### PR DESCRIPTION
**Pull request by cyan33**
In https://github.com/facebook/react/pull/13105, `Timeout` has been changed to `Placeholder`. Also, the usage has been slightly changed.

Would love to collaborate on some new library idea with suspense.

### CODE REVIEW

**Comment by threepointone** [comment]
Ah, I was using an older build of react, thanks! Happy to chat anytime, I’m on workplace too

**Comment by threepointone** [comment]
Chang, my example seems to render the fallback text immediately, implying it's in sync mode. would you mind having a look at my code and telling what I'm doing wrong? I built react with `enableSuspense = true` in ReactFeatureFlags, anything else I'm supposed to do for async mode? cc @acdlite plsthx!

**Comment by threepointone** [comment]
solved! https://github.com/threepointone/css-suspense/commit/da30c11752bda061f947694c13d2c31618a8a376

**Comment by cyan33** [comment]
Yeah `unstable_createRoot` implies async mode.
You could also try wrap the `<Stylesheet />` with a `React.unstable_AsyncMode` wrapper. I think it'll work the same.

**Comment by threepointone** [comment]
apparently just using asyncmode doesn't work for first render, it has to be rendered via createroot.

**Pull request merged**
